### ISSUE TITLE
DSM 6.1

### ISSUE THREAD

**Issue by niXta1** [remonlam/synology-data-scrubbing#2]
admin@NASSE:/volume1$ ./data_scrub.sh
Missing argument DEVICE. Eg: md0 md1, md2, etc.

-rwxr-xr-x   1 root            root                386 Feb  9 09:22 data_scrub.sh

Not sure why it does not work? Any Ideas?

**Comment by remonlam** [comment]
@niXta1 I think you forgot to tell the script what volume it needs to scrub.
It should be something like **md0**, **md1**, **md2** etc", use `cat /proc/mdstat` to display the volumes.

Here's a sample of my scheduled task `/volume1/start_data_scrubbing.sh md0 md1 md2 md3`

Hope this helps!

**Comment by niXta1** [comment]
Sorry for being an idiot! :)

Would it not be possible to integrate `cat /proc/mdstat` extract all mdx and use that for input in the script?

Regardless, thank you!

**Comment by remonlam** [comment]
Haha no problem ;-)
Yeah that sounds like a great idea, will put it on my to do list!

**Comment by mchubby** [comment]
Hello,
can you update screenshot `docs/create_task_5.png` to reflect the required agument (as instructed in the associated paragraph)?
Currently it has no argument in the scheduler job.
